# 配置文件加密key
jasypt:
  encryptor:
    password: monkeyzi

server:
  port: 8081
spring:
  application:
    name: @artifactId@
  datasource:
      url: jdbc:mysql://monkeyzi:3306/monkeyboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: guoguo
      password: ENC(ly6ALRqFlY9vVwnabWCg+5j/J7PdUuHe)
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
  #exception
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  #redis
  redis:
    host: 127.0.0.1
    #password: ENC(sAxR1yuo9TKgVO4rpYtgEw==)
    password:
    port: 6379
    jedis:
      pool:
        max-wait: 5000ms
        min-idle: 8
        max-idle: 50
        max-active: 8
## spring security 配置
security:
  oauth2:
    client:
      client-id: mboot
      client-secret: mboot
      scope: server
      # 默认放行url,子模块重写时application-dev.yml中的公共配置会被覆盖,所以要把公共配置中的放行url再写一次
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /token/**
        - /mobile/**
        - /swagger/api-docs
        - /swagger-ui.html
        - /swagger-resources/**
        - /webjars/**

#mybatis plus配置
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      # 主键类型  AUTO(0),NONE(1),INPUT(2),ID_WORKER(3),UUID(4),ID_WORKER_STR(5);
      id-type: auto
      # 逻辑删除配置（下面3个配置）使用的时候在字段上加上@TableLogic  0默认不删除  1删除
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 数据库类型
      db-type: mysql
      #字段验证策略  默认也是NOT_NULL
      field-strategy: default
    # 关闭mp banner 启动的时候不让在控制台打印
    banner: false
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    #开发驼峰命名转化
    map-underscore-to-camel-case: true
    # 是否开启缓存
    cache-enabled: false
  #别名
  type-aliases-package: com.monkeyzi.mboot.entity

# swagger配置
swagger:
  title: Mboot Swagger API
  description: Mboot在线API文档
  version: 0.0.1-SNAPSHOT
  license: Powered By monkeyzi
  licenseUrl: http://www.monkeyzi.xin
  terms-of-service-url: http://www.monkeyzi.xin
  contact:
    name: monkeyzi
    email: 854152531@qq.com
    url: http://www.monkeyzi.xin
  authorization:
    name: Mboot OAuth
    auth-regex: ^.*$
    authorization-scope-list:
      - scope: server
        description: server all
    token-url-list:
      - http://127.0.0.1:8081/oauth/token
  base-package: com.monkeyzi.mboot.controller